language: java
dist: trusty
jdk: oraclejdk8
addons:
  apt:
    packages:
      - oracle-java9-installer
script: "mvn cobertura: cobertura"
before_install:
  - chmod +x mvnw
after_success:
  - bash <(curl -s https://codecov.io/bash)